// ── COMPLIANCE ────────────────────────────────────────────────────────

function generateReport(type) {
  const names = {
    cpcb:  'CPCB Monthly Report — Jun 2026',
    bmwm:  'BMWM Manifest Data — Jun 2026',
    audit: 'Audit Trail Export — Jun 2026',
    esg:   'ESG Sustainability Report — Q2 2026',
  };
  const sizes = { cpcb:'2.4 MB', bmwm:'8.1 MB', audit:'1.1 MB', esg:'3.2 MB' };

  openModal('Generate Report', `
    <div style="text-align:center;padding:20px 0">
      <div id="report-progress" style="margin-bottom:16px">
        <div style="font-size:32px;margin-bottom:8px"><i class="fa fa-file-pdf" style="color:var(--red)"></i></div>
        <div style="font-weight:600;margin-bottom:4px">${names[type] || 'Report'}</div>
        <div style="font-size:12px;color:var(--text-3);margin-bottom:16px">Compiling data across all hospitals...</div>
        <div style="height:6px;background:var(--bg-3);border-radius:3px;overflow:hidden;max-width:300px;margin:0 auto">
          <div id="report-bar" style="height:100%;width:0%;background:var(--green);border-radius:3px;transition:width 0.3s"></div>
        </div>
        <div id="report-pct" style="font-size:12px;color:var(--text-3);margin-top:6px">0%</div>
      </div>
      <div id="report-done" style="display:none">
        <div style="font-size:32px;margin-bottom:8px"><i class="fa fa-check-circle" style="color:var(--green)"></i></div>
        <div style="font-weight:600;margin-bottom:4px">${names[type]} ready</div>
        <div style="font-size:12px;color:var(--text-3);margin-bottom:16px">Size: ${sizes[type] || '2.0 MB'} · Generated: ${new Date().toLocaleString('en-IN')}</div>
        <div style="display:flex;gap:8px;justify-content:center">
          <button class="btn-primary" onclick="simulateDownload('${names[type]}')"><i class="fa fa-download"></i> Download</button>
          <button class="btn-secondary" onclick="closeModal()">Close</button>
        </div>
      </div>
    </div>
  `);

  // Animate progress bar
  let pct = 0;
  const bar = document.getElementById('report-bar');
  const pctEl = document.getElementById('report-pct');
  const interval = setInterval(() => {
    pct += Math.random() * 18 + 8;
    if (pct >= 100) {
      pct = 100;
      clearInterval(interval);
      if (bar) bar.style.width = '100%';
      if (pctEl) pctEl.textContent = '100%';
      setTimeout(() => {
        const prog = document.getElementById('report-progress');
        const done = document.getElementById('report-done');
        if (prog) prog.style.display = 'none';
        if (done) done.style.display = 'block';
        // Add to reports list
        EY.reports.unshift({
          name: names[type], type: type.toUpperCase(), period: 'Jun 2026',
          hospital: 'All Hospitals',
          generated: new Date().toLocaleString('en-IN', { day:'2-digit', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }),
          size: sizes[type] || '2.0 MB', status: 'READY'
        });
        loadReports();
      }, 400);
    } else {
      if (bar) bar.style.width = pct + '%';
      if (pctEl) pctEl.textContent = Math.floor(pct) + '%';
    }
  }, 120);
}

function simulateDownload(name) {
  closeModal();
  showToast('Downloading: ' + name, 'success');
  // Create a simple text file as demo download
  const content = `EcoYantra Report\n================\n${name}\nGenerated: ${new Date().toLocaleString('en-IN')}\n\nThis is a demo export. In production, this would be a fully formatted PDF/Excel generated by the NestJS backend using Puppeteer or ExcelJS.\n\nWaste Summary June 2026\n-----------------------\nYellow (Anatomical): 28,420 kg\nRed (Recyclable):    38,210 kg\nWhite (Sharps):      17,900 kg\nBlue (Glass/Metal):  13,800 kg\nTotal:               98,330 kg\n\nCompliance Score: 94.7%\nWDI: 2.3% (target <5%)\nViolations: 3 open\n\nGenerated by EcoYantra Platform v1.0\nwww.ecoyantra.com | contact@ecoyantra.com`;
  const a = document.createElement('a');
  a.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent(content);
  a.download = name.replace(/[^a-z0-9]/gi, '_') + '.txt';
  a.click();
}
