// ── QR MANAGEMENT ─────────────────────────────────────────────────────
let scannerStarted = false;

function loadScanHistory() {
  document.getElementById('scan-history-tbody').innerHTML = EY.scanHistory.slice(0,6).map(s => `
    <tr>
      <td><span style="font-family:monospace;font-size:11px">${s.code}</span></td>
      <td>${catBadge(s.category)}</td>
      <td>${s.weight}</td>
      <td>${s.by}</td>
      <td><span class="badge ${s.action==='DISPOSED'?'s-neutral':s.action==='GENERATED'?'s-info':'s-ok'}">${s.action}</span></td>
      <td>${s.time}</td>
      <td>${statusBadge(s.action === 'DISPOSED' ? 'DISPOSED' : s.action === 'GENERATED' ? 'GENERATED' : 'COLLECTED')}</td>
    </tr>
  `).join('');
}

function loadFullScanHistory() {
  document.getElementById('full-scan-tbody').innerHTML = EY.scanHistory.map(s => `
    <tr>
      <td><span style="font-family:monospace;font-size:11px">${s.code}</span></td>
      <td><span style="font-family:monospace;font-size:11px">${s.code}</span></td>
      <td>${catBadge(s.category)}</td>
      <td><span class="badge ${s.action==='DISPOSED'?'s-neutral':s.action==='GENERATED'?'s-info':'s-ok'}">${s.action}</span></td>
      <td>${s.by}</td>
      <td>${s.location}</td>
      <td>${s.time} · 10 Jun 2026</td>
    </tr>
  `).join('');
}

function startScanner() {
  if (scannerStarted) return;
  scannerStarted = true;
  const placeholder = document.getElementById('qr-placeholder');
  if (placeholder) placeholder.style.display = 'none';

  if (typeof Html5Qrcode === 'undefined') {
    showToast('QR scanner library not loaded. Enter code manually.', 'warn');
    if (placeholder) placeholder.style.display = 'block';
    scannerStarted = false;
    return;
  }

  const html5QrCode = new Html5Qrcode('qr-reader');
  html5QrCode.start(
    { facingMode: 'environment' },
    { fps: 10, qrbox: { width: 250, height: 250 } },
    (decodedText) => {
      html5QrCode.stop();
      scannerStarted = false;
      document.getElementById('manual-qr-input').value = decodedText;
      lookupQR();
      showToast('QR code scanned: ' + decodedText, 'success');
    },
    (err) => { /* scanning frame error — ignore */ }
  ).catch(err => {
    showToast('Camera access denied. Use manual entry.', 'warn');
    if (placeholder) placeholder.style.display = 'block';
    scannerStarted = false;
  });
}

function lookupQR() {
  const code = document.getElementById('manual-qr-input').value.trim().toUpperCase();
  const panel = document.getElementById('qr-result-panel');

  if (!code) { panel.innerHTML = '<div class="empty-state"><i class="fa fa-qrcode"></i><div>Enter a waste code to look up</div></div>'; return; }

  const rec = EY.wasteRecords.find(w => w.id === code);

  if (!rec) {
    panel.innerHTML = `<div class="empty-state"><i class="fa fa-circle-xmark" style="color:var(--red)"></i><div>No record found for <strong>${code}</strong></div></div>`;
    showToast('QR code not found: ' + code, 'error');
    return;
  }

  const catDotColor = { YELLOW:'#EF9F27', RED:'#E24B4A', WHITE:'#94a3b8', BLUE:'#378ADD' };

  panel.innerHTML = `
    <div class="qr-result-card">
      <div class="qr-result-header">
        <div class="qr-cat-dot" style="background:${catDotColor[rec.category]}"></div>
        <div class="qr-code-text">${rec.id}</div>
        ${statusBadge(rec.status)}
      </div>
      <div class="qr-result-grid">
        <div class="qr-detail-item"><div class="qr-detail-label">Category</div><div class="qr-detail-val">${catBadge(rec.category)}</div></div>
        <div class="qr-detail-item"><div class="qr-detail-label">Weight</div><div class="qr-detail-val">${rec.weight} kg</div></div>
        <div class="qr-detail-item"><div class="qr-detail-label">Department</div><div class="qr-detail-val" style="font-size:11px">${rec.dept.split('—')[0]}</div></div>
        <div class="qr-detail-item"><div class="qr-detail-label">Generated By</div><div class="qr-detail-val">${rec.by}</div></div>
        <div class="qr-detail-item"><div class="qr-detail-label">Date</div><div class="qr-detail-val">${rec.date}</div></div>
        <div class="qr-detail-item"><div class="qr-detail-label">Location</div><div class="qr-detail-val" style="font-size:11px">${rec.location||'—'}</div></div>
      </div>
      <div class="qr-action-row">
        <button class="btn-primary btn-sm" onclick="confirmScanAction('${rec.id}')"><i class="fa fa-check"></i> Confirm Collection</button>
        <button class="btn-secondary btn-sm" onclick="viewLifecycle('${rec.id}')"><i class="fa fa-timeline"></i> Track</button>
      </div>
    </div>
  `;

  // Log scan
  EY.scanHistory.unshift({
    code: rec.id, category: rec.category, weight: rec.weight + ' kg',
    by: JSON.parse(localStorage.getItem('ey_user')||'{}').name || 'Staff',
    action: 'SCANNED', location: 'Manual entry', time: new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})
  });
  loadScanHistory();
}

function confirmScanAction(id) {
  openModal('Confirm Collection — ' + id, `
    <div style="margin-bottom:14px;padding:10px;background:var(--green-light);border-radius:8px;font-size:13px;color:var(--green-dark)">
      <i class="fa fa-check-circle"></i> Confirm that waste bag <strong>${id}</strong> has been physically collected.
    </div>
    <div class="form-field"><label>GPS Location (optional)</label><input type="text" placeholder="Auto-detected or enter manually" value="19.0760°N, 72.8777°E" /></div>
    <div class="form-field" style="margin-top:10px"><label>Collection Staff ID</label><input type="text" placeholder="Your staff ID" /></div>
    <div class="form-field" style="margin-top:10px"><label>Weight Verification (kg)</label><input type="number" placeholder="Confirm weight at pickup" step="0.01" /></div>
    <div class="form-actions">
      <button class="btn-primary" onclick="doConfirmCollection('${id}')"><i class="fa fa-check"></i> Confirm Collection</button>
      <button class="btn-secondary" onclick="closeModal()">Cancel</button>
    </div>
  `);
}

function doConfirmCollection(id) {
  const rec = EY.wasteRecords.find(w => w.id === id);
  if (rec) {
    rec.status = 'COLLECTED';
    loadWasteTable();
    loadLifecycleTable();
    EY.scanHistory.unshift({
      code: id, category: rec.category, weight: rec.weight + ' kg',
      by: JSON.parse(localStorage.getItem('ey_user')||'{}').name || 'Staff',
      action: 'COLLECTED', location: 'AIIMS Mumbai', time: new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})
    });
    loadScanHistory();
  }
  closeModal();
  showToast(id + ' marked as COLLECTED', 'success');
  // Clear result panel
  document.getElementById('qr-result-panel').innerHTML = '<div class="empty-state"><i class="fa fa-check-circle" style="color:var(--green)"></i><div>Collection confirmed. Scan next bag.</div></div>';
  document.getElementById('manual-qr-input').value = '';
}

function generateQRLabel() {
  const sel   = document.getElementById('qr-gen-select');
  const count = parseInt(document.getElementById('qr-label-count').value) || 1;
  const id    = sel.value;
  if (!id) { showToast('Select a waste record first', 'warn'); return; }

  const rec = EY.wasteRecords.find(w => w.id === id);
  if (!rec) return;

  const catColors = { YELLOW:'#EF9F27', RED:'#E24B4A', WHITE:'#94a3b8', BLUE:'#378ADD' };
  const catLabels = { YELLOW:'INCINERATION ONLY', RED:'AUTOCLAVING', WHITE:'SHARPS — AUTOCLAVE+SHRED', BLUE:'STERILIZATION' };

  let labelsHTML = '';
  for (let i = 0; i < Math.min(count, 4); i++) {
    labelsHTML += `
      <div class="qr-label" style="margin:6px;display:inline-block">
        <div class="qr-label-header">
          <span style="font-size:10px">ECOYANTRA</span>
          <span style="color:${catColors[rec.category]};font-size:10px">${rec.category}</span>
        </div>
        <div class="qr-label-code">${rec.id}${i > 0 ? '-' + (i+1) : ''}</div>
        <div id="qr-gen-${i}" style="margin:6px auto;width:80px"></div>
        <div class="qr-label-details" style="font-size:9px">
          <div>Dept: ${rec.dept.split('—')[0].trim()}</div>
          <div>Wt: ${rec.weight} kg · Qty: ${rec.qty}</div>
          <div>By: ${rec.by}</div>
        </div>
        <div class="qr-label-footer" style="color:${catColors[rec.category]};font-size:8px">${catLabels[rec.category]}</div>
      </div>
    `;
  }

  document.getElementById('qr-preview-area').innerHTML = `
    <div style="margin-bottom:8px;font-size:12px;font-weight:500">Preview (${count} label${count>1?'s':''})</div>
    <div>${labelsHTML}</div>
  `;

  // Generate QR codes
  setTimeout(() => {
    for (let i = 0; i < Math.min(count, 4); i++) {
      const el = document.getElementById(`qr-gen-${i}`);
      if (el && typeof QRCode !== 'undefined') {
        new QRCode(el, { text: rec.id + (i > 0 ? '-' + (i+1) : ''), width: 80, height: 80, colorDark:'#000', colorLight:'#fff', correctLevel: QRCode.CorrectLevel.M });
      }
    }
  }, 100);

  showToast(`${count} QR label(s) generated`, 'success');
}

function printQRLabel() {
  const area = document.getElementById('qr-preview-area');
  if (!area.innerHTML.trim()) { showToast('Generate labels first', 'warn'); return; }
  window.print();
  showToast('Sent to printer', 'success');
}
